### ISSUE TITLE
DeploymentOperations polling failed

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#110]
While doing a deployment I got DeploymentOperations polling failed. It is deploying stack on MG scope and resources to a subscription with -Verbose option.

![image](https://github.com/Azure/deployment-stacks/assets/11890856/fc77b405-92d4-449d-aa7a-254f9b85ee97)

**Comment by slavizh** [comment]
Every time I run the same command I get the same error. This seems like a bug.

**Comment by Xynoclafe** [comment]
@slavizh Are we hitting a non-terminal state with these stack deployments? Or is it that polling itself is always failing?

**Comment by slavizh** [comment]
@Xynoclafe just on polling. I think this is a bug with deployment stack at management group scope with deployment of the resources happening at subscription scope as the same template works fine if the deployment stack is done on subscription scope. There is possibility that the same bug present at doing deployment stack at subscription scope but resource being deployed at resource group scope. I have not tested it but you can check out.

**Comment by dantedallag** [comment]
Hey @slavizh is this happening for you with this specific template or with all MG level stack deployments? I am able to deploy an MG stack with a deployment at the subscription level and am not seeing this "polling failed" message.

**Comment by slavizh** [comment]
@dantedallag yeah, I have tested with one template. Hadn't time to check with more. If needed I can send the template and input parameters for reproduction in private.

**Comment by dantedallag** [comment]
@slavizh If you could email the template and input parameters, that would be great. Also, trying some other templates would be helpful too, just to see if we can pinpoint whether this issue seems to be related to template content.

**Comment by slavizh** [comment]
@dantedallag I have send you e-mail.

**Comment by slavizh** [comment]
Send another template that reproduces this issue.

**Comment by aperezmicrosoft** [comment]
Hi @slavizh - we were not able to repro this issue with both of the templates provided. Are you still running into this issue? We wonder if this is being caused due to replication delays rather than the service itself.

**Comment by slavizh** [comment]
Hi @azcloudfarmer  I can still reproduce the issue every time. Is there something I can do to debug this instead of you?

![image](https://github.com/Azure/deployment-stacks/assets/11890856/26417524-6948-4898-9ac9-53ff970ec3d1)

![image](https://github.com/Azure/deployment-stacks/assets/11890856/db8519b0-7c71-46df-a4e8-07e62892fbee)

**Comment by slavizh** [comment]
@dantedallag  @azcloudfarmer I can report that I cannot reproduce the issue as well. Either it was fixed on the backend or in the latest Az PS release. Issue can be closed.
