### ISSUE TITLE
Remove-AzManagementGroupDeploymentStack does not work correctly with Get-AzManagementGroupDeploymentStack

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#111]
You should not get error when you do it like this:

```
PS D:\dev\deployment-stacks\lz-policy-management> Get-AzManagementGroupDeploymentStack -ManagementGroupId Sponsor | Remove-AzManagementGroupDeploymentStack
Remove-AzManagementGroupDeploymentStack: The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  ManagementGroupId
```

as the first command contains the management group the passed object should just be removed as you have at which MG the stack is.

**Comment by dantedallag** [comment]
Hey @slavizh, this should be included in the PowerShell release next month.

**Comment by dantedallag** [comment]
New release is out and this should be fixed. Let us know if you are still seeing this.
