### ISSUE TITLE
Default table output should not include `Resource IDs`

### ISSUE THREAD

**Issue by alex-frankel** [Azure/deployment-stacks#112]
I don't think it's relevant in the list view to see the managed resource IDs. More often than not, there will be too many resource IDs to list and the table will be too cluttered to be effective:

![image](https://github.com/Azure/deployment-stacks/assets/11078275/0e9a6bf3-2513-4c96-a7ea-ab36d70a11ba)

**Comment by harshpatel17** [comment]
I agree, I added an item to track. https://msazure.visualstudio.com/One/_sprints/taskboard/Azure-ARM-Deployments/One/Custom/Azure-ARM/Gallium/Jun-2023?workitem=24468095

**Comment by harshpatel17** [comment]
Issue resolved, removed ids from show and list table outputs. Released in Azure CLI 2.51.0
