### ISSUE TITLE
`--deny-settings-mode` should have a shortcut

### ISSUE THREAD

**Issue by alex-frankel** [Azure/deployment-stacks#114]
From the az CLI stacks help text, `--deny-settings-mode` does not have a shortcut. It would be great if it had one given it is a required parameter.

**Comment by aperezmicrosoft** [comment]
@harshpatel17 we can try --dm or --ds

**Comment by harshpatel17** [comment]
Added a ticket for this, will be included in the upcoming release cycle.

**Comment by harshpatel17** [comment]
https://msazure.visualstudio.com/One/_sprints/taskboard/Azure-ARM-Deployments/One/Custom/Azure-ARM/Gallium/Jun-2023?workitem=24493373

**Comment by harshpatel17** [comment]
Issue resolved, shortcut added and released in Azure CLI 2.51.0
