### ISSUE TITLE
Deployment Stack Parameters does not support .bicepparm files

### ISSUE THREAD

**Issue by JFolberth** [Azure/deployment-stacks#121]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Be able to pass in a .bicepparam file to the stack

**Describe alternatives you've considered**

**Additional context**

**Comment by dantedallag** [comment]
Hi @JFolberth, our New/Set cmdlets should be supporting .bicepparam files by passing it in the TemplatesParameterFile parameter as you would do a json parameter file. Could you share the exact command you are using that is running into this issue? Also, could you share the version of stacks you are using by outputting the Az.Resources version with 'Get-InstalledModule -Name Az.Resources'?

**Comment by JFolberth** [comment]
@dantedallag 

Sure,

The command: `az stack sub create --name 'storageAccounts' --location 'eastus' --template-file 'main.bicep' --parameters parameters/dev.eus.parameters.bicep --deny-settings-mode 'none'`

and the Az.Resources version is 6.9.1

**Comment by harshpatel17** [comment]
Hi @JFolberth would you be able to share your bicep parameter file? 

I believe we only support bicep parameter files that have the extension type .bicepparam not .parameters.bicep.

**Comment by JFolberth** [comment]
@harshpatel17  sure.

This is all the content is:

```using '../main.bicep'
param location = 'eastus'
param environmentName= 'dev'
param storageAccountType = 'Standard_LRS'
param numberOfStorageAccounts = 2
```

I would think this might be a bug then vs new feature since ARM did support this. The use case is leveraging a "." vs an "_"  file naming convention since the  "_" lacks in support when recognizing file names. There are multiple customers i have worked with who label ARM files like dev.parameters.json and one would imagine the equivalent would be dev.parameters.bicepparam

**Comment by JFolberth** [comment]
Can ignore this. I had typed the file name wrong :(
