### ISSUE TITLE
Deployment stack stuck Initializing

### ISSUE THREAD

**Issue by Grant-Rc** [Azure/deployment-stacks#128]
**Describe the bug**
Deploying a basic test of 1 RG and 1 vNet and its stuck Initializing because i mistakenly used an invalid address prefix

**To Reproduce**
`az stack sub create `
   --name 'testing1' `
   --location $Location `
   --template-file .\deploy\main-example-rg.bicep `
   --parameters .\parameters\deploy-example-rg.parameters.json `
   --deny-settings-mode 'denyWriteAndDelete'`

Bicep
`targetScope = 'subscription'

param location string = deployment().location
param Tags object

module rgCreation1 '../modules/Microsoft.Resources/resourceGroups/deploy.bicep' = {
  name: 'rg-deployment-1'
  params: {
    tags: Tags
    location: location
    name: 'testing1'
  }
}

module vnet1 '../modules/Microsoft.Network/virtualNetworks/deploy.bicep' = {
  scope: resourceGroup('testing1')
  name: 'vnet-deploy-1'
  params: {
    location: location
    addressPrefixes: [
      '10.300.0.0/26'
    ]
    name: 'test-tobedeleted-1'
  }
}`

**Expected behavior**
Error out

**Screenshots**
<img width="489" alt="image" src="https://github.com/Azure/deployment-stacks/assets/3213940/1f1845a8-f461-4a31-9f8a-7a8047558692">

**Repro Environment**
Host OS: Windows 11
Powershell Version: 7
az 2.52

**Server Debugging Information**
Correlation ID: na
Tenant ID: na
Timestamp of issue (please include time zone):  
21 Sept 2023, 11:47 am NZst
Data Center (eg, West Central US, West Europe):
Australia East

**Additional context**
tried to also delete the stack but errors out with

(DeploymentStackResourceConflict) The deployment stack cannot be updated while it's in a non-terminal state.
Code: DeploymentStackResourceConflict
Message: The deployment stack cannot be updated while it's in a non-terminal state.

**Comment by snarkywolverine** [comment]
@Grant-Rc If it is still stuck in 'creating' or 'initializing', can you please share the subscription and resource group of the stack? Once we have that info, we can mark it as 'failed' so you can reattempt the deployment.

**Comment by Grant-Rc** [comment]
@snarkywolverine that would be great as they are still "stuck"
0ac17b55-1d59-4646-848c-637430e18516
![image](https://github.com/Azure/deployment-stacks/assets/3213940/546b52ac-5679-475c-bf9f-2d9d3d57891e)
even 1 stuck in deleting

**Comment by dantedallag** [comment]
@Grant-Rc I was able to reset all 4 of these stacks. Let me know if this resolves your issue. We will look more into the root issue.

**Comment by Grant-Rc** [comment]
> @Grant-Rc I was able to reset all 4 of these stacks. Let me know if this resolves your issue. We will look more into the root issue.

Thank you @dantedallag, I was able to remove the stacks, Any idea how to remove the RG now though? I did asked the stack delete to also delete the RG but it was left behind.

Still has the deny assignment for the deleted stack
![image](https://github.com/Azure/deployment-stacks/assets/3213940/adc562d1-338b-44a1-869d-c2c98beae739)

**Comment by Grant-Rc** [comment]
FYI - have also logged a support ticket to get help with this RBAC - TrackingID#2309260030005747

**Comment by aperezmicrosoft** [comment]
Hi @Grant-Rc - we are in contact with the support team on this case. We are working towards a resolution and will get back to you within the next 72 hours.

**Comment by Grant-Rc** [comment]
> Hi @Grant-Rc - we are in contact with the support team on this case. We are working towards a resolution and will get back to you within the next 72 hours.

Sounds good cause I just had Kefei Yang (Shanghai Wicresoft Co,.Ltd.) contact me via Teams if you can also work with them

**Comment by dantedallag** [comment]
@Grant-Rc I believe I was able to delete it. Could you confirm?

**Comment by Grant-Rc** [comment]
> @Grant-Rc I believe I was able to delete it. Could you confirm?

yes, thank you 
![image](https://github.com/Azure/deployment-stacks/assets/3213940/6600aad6-5988-4674-a951-59d51318e0e9)

Can you also remove the one from the other RG in the same subscription please
![image](https://github.com/Azure/deployment-stacks/assets/3213940/9b380c13-6c98-49ca-93a8-6f8e5d726e02)

I assume going forward there will be an option or something?

**Comment by snarkywolverine** [comment]
Under normal circumstances, the deny assignment will be managed automatically by the deployment stack.

In this case, the reset command failed to track the resources (and deny assignments) from the previous iteration of the stack, which is how you ended up not being able to remove the resource group.

**Comment by dantedallag** [comment]
@Grant-Rc Can you confirm that the deny assignment was deleted?

**Comment by aperezmicrosoft** [comment]
Hi @Grant-Rc - can you confirm deletion of the deny assignment on your end? Thanks!

**Comment by aperezmicrosoft** [comment]
@Grant-Rc friendly ping/reminder

**Comment by Grant-Rc** [comment]
sorry team i was away. Yep the assignment and the RG was removed, thank you for all your help
