### ISSUE TITLE
Making the generated module names shorter

### ISSUE THREAD

**Issue by antsok** [Azure/deployment-stacks#129]
**Is your feature request related to a problem? Please describe.**
Some of our code cannot be deployed with stacks because of exceeding the 64 character limitation on resource module naming. This happens because stacks add 'YYYY-mm-dd-HH-MM-ss-xxxxx' string to the name of the bicep deployment it originates, and as we are using '${deployment().name}-something' to name our modules all of this together exceeds 64 characters sometimes.

**Describe the solution you'd like**

By default, shorten the string from 'YYYY-mm-dd-HH-MM-ss-xxxx' to something like 'YYYYmmddHHMMss-xxxxx' already 'saves' 5 characters.

It would be more convenient to give control to the caller if to make generated module names unique, or if it ok not to do so.

**Describe alternatives you've considered**
Changing our bicep modules implementation.

**Additional context**

**Comment by aperezmicrosoft** [comment]
Hi @antsok can you please share the correlationID for this failure if any?

**Comment by aperezmicrosoft** [comment]
What is the context of the creation of this Module (Assuming you are referring to BICEP modules)?

**Comment by Sdelausnay** [comment]
Hi, I have the same issues.

Wanted to switch to stack as deployment but we are using a lot of Bicep Modules. We have created a structure where we use deployement.name() to create the names of our modules. But indeed seems stacks is adding a lot of stuff to the deployment name like "YYYY-mm-dd-HH-MM-ss-xxxx". Would there be a possibility to skip these added values in the deployment name from the stack? 

In the past, if we provided a name to 
`az deployment sub create --name '$(Build.BuildNumber)`
We would end up with a deployment name like 
`20230930.02-preview-coditoc-network-net-1-application0-gr`

But now with deployment stack 
 ` az stack sub create  --name '$(Build.BuildNumber)'`
We end up with 
 ` 20230930.01-preview-2023-09-30-21-42-44-e8f95-co`

Which is to long so they are cut ending up with multiple deployment names. 

Correlation id: '3d81457f-0e9f-446a-afd2-6c0986013c76'

**Comment by antsok** [comment]
> Hi @antsok can you please share the correlationID for this failure if any?

Hi. Unfortunately, the original one is now not available, so I've reproduced it anew. The id: b6b90254-2ba0-4432-9c08-97a66d3cfb9c

**Comment by antsok** [comment]
> What is the context of the creation of this Module (Assuming you are referring to BICEP modules)?

az stack sub create --name ado-aca ...  --template-file main.bicep ...

main.bicep deployment gets a long name from `az stack`. Example: `ado-aca-2023-09-30-23-07-26-240ba`

main.bicep with subscription target scope is using a bicep module with resource group scope.

```
module acr 'acr.bicep' = {
  scope: rg
  name: '${deployment().name}-acr-verylongstringattheendtomakeitfail' // <-- here
  params: {
    location: location
    enableAutoscaling: true
    ghBranch: ghBranch
  }
}
```

acr.bicep deployment uses the current module's deployment name to construct the submodule name.

`The provided deployment name 'ado-aca-2023-09-30-23-07-26-240ba-acr-verylongstringattheendtomakeitfail' has a length of '72' which exceeds the maximum length of '64'.`

**Comment by MassimoC** [comment]
it would be nice to add an optional parameter --deployment-name and give the user the choice to decide to be in control of the deployment name or not

**Comment by aperezmicrosoft** [comment]
Hello @antsok - thanks for sharing the details. We recognize the issue can be solved with the use of the [uniqueString](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-string#uniquestring) function along with preferred suffix. 

For reference, we are considering making the name optional on Bicep modules in the future. Here is the tracking item: https://github.com/Azure/bicep/issues/3897

**Comment by antsok** [comment]
Without the fix on deployment stacks end, the only other solution is to change our own bicep modules. This means time and investment, and we would probably not do it, sticking to the previous ways of deployment.

**Comment by alex-frankel** [comment]
we need to add *something* to the deployment name so we don't automatically overwrite the previous deployment. Is there an acceptable number of characters you all would be comfortable with?

**Comment by antsok** [comment]
'YYmmddHHMMss' as an added prefix before/after the deployment name would be ok, imo.

**Comment by alex-frankel** [comment]
So 12 characters is good enough, and 24 characters is too much. Anyone think 12 characters is still too much? Trying to understand what we need to optimize for.

**Comment by antsok** [comment]
Winning 12 characters back would already help us.

However, having a possibility of providing the unique prefix ourselves (we are using ADO pipeline run id for this) would be the best option. A separate parameter, maybe, that when provided is used instead of the current timestamp.

**Comment by alex-frankel** [comment]
To follow up on this, we had a discussion to shorten the generated module to the following format: 

`<stackName>YYmmddhh<XXXX>` 

where `XXXX` is a Base36 hash for "extra" uniqueness to avoid conflicts. That reduces the characters we suffix from 24 to 12. Please let us know if that is still too many characters. I will create a separate issue to track the ask of a command line argument to supply your own custom suffix.

**Comment by antsok** [comment]
I think this will be a good improvement already.

**Comment by MassimoC** [comment]
>  I will create a separate issue to track the ask of a command line argument to supply your own custom suffix.

hi @alex-frankel, just wondering ... why do you prefer passing a custom suffix and not a full deployment name? thanks

**Comment by alex-frankel** [comment]
Let's discuss it in #133. I don't personally have a strong opinion on how it should work, I just wanted to keep the asks separate.

That being said, it can't just be a static name. It needs to be dynamic for each stack deployment or we would overwrite the previous deployment.

**Comment by aperezmicrosoft** [comment]
Adding work item reference: https://msazure.visualstudio.com/One/_backlogs/backlog/Azure-ARM-Deployments/Features/?workitem=25651683

**Comment by snarkywolverine** [comment]
This change has been rolled out to all public regions, with government clouds to follow shortly.  The character count ended up appending 14 characters (down from 24).

**Comment by antsok** [comment]
This works smoothly for us now. Many thanks @alex-frankel and the team!
