### ISSUE TITLE
I'd like the ability to see the progress of resource deletions

### ISSUE THREAD

**Issue by hallgeir-osterbo-ac** [Azure/deployment-stacks#130]
**Is your feature request related to a problem? Please describe.**
When there are many resources to be deleted in a deployment, it can take some time (much more time than it takes when deleting stuff manually through the portal in my experience). In those situations, it would be REALLY useful to see the progress of deletions. It's a bit frustrating to see the deployment itself being green, but the deployment stack is still not done deploying for a long long time while it's attempting to delete resources. Deletions can also fail for various reasons (e.g. due to resource locks or other reasons), and then it would be good to see the status "live".

There's also an issue with the status for the deployment stack, which just shows as empty while it's deleting resources.

Better error messages for resource deletion would also be very welcome. "An unknown error occurred while trying to delete resources" is not extremely helpful. But that may be better to track here: https://github.com/Azure/deployment-stacks/issues/124

**Describe the solution you'd like**
One suggestion would be to show a list of resources that are going to be deleted in the deployment stack itself in the portal, and the status for each of them. I'm sure there can be other even better ways of solving this though.

**Describe alternatives you've considered**
I don't have any alternatives at this time. As it is now, we just have to wait and be (very) patient. :-)

**Additional context**

**Comment by aperezmicrosoft** [comment]
Hi @hallgeir-osterbo-visma - thank you for the details. We are already tracking this suggestion here in: https://github.com/Azure/deployment-stacks/issues/107
