### ISSUE TITLE
Deployment Stacks, unable to Add an existing resource (ie created outside of Bicep) into Deployment Stack

### ISSUE THREAD

**Issue by lukemurraynz** [Azure/deployment-stacks#146]
Bicep version
Bicep CLI version 0.24.24

Describe the bug
Deployment Stacks, unable to Add an existing resource (ie created outside of Bicep) into Deployment Stack

To Reproduce

Bicep;

param stgnamme string = 'stfacc1337'

resource storage 'Microsoft.Storage/storageAccounts@2023-01-01' existing = {
name: stgnamme
scope: resourceGroup('deploymentstacks-rg')
}

-- Along with other resources, that are deployed from Bicep, that are in the Deployment Stack.

Using the following commands: Set-AzResourceGroupDeploymentStack -Name "MyRGStack"
-ResourceGroupName "deploymentstacks-rg" -TemplateFile "main.bicep"
-DenySettingsMode "DenyDelete"

**Comment by lukemurraynz** [comment]
I got it working, by [Inserting the resource into Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/visual-studio-code?tabs=CLI&WT.mc_id=AZ-MVP-5004796#insert-resource), instead of using the Existing flag.

**Comment by alex-frankel** [comment]
Thanks Luke - FWIW, this is the expected behavior. `existing` is only a reference to a resource that you are intentionally not deploying in the stack, so we make sure not to add it to the list of managed resources.
