### ISSUE TITLE
Install only works in certain circumstances, consider making more generic

### ISSUE THREAD

**Issue by brwilkinson** [Azure/deployment-stacks#16]
**Describe the bug**
If you install the az module with PowerShell 5 it uses 1 version of PowerShellGet
If you install the az module with PowerShell 7 it uses a different verson of PowerShellGet
- depending on which version you use, it places the metadata used to track what was installed in different places, so they cannot be detected via the other version

Consider replacing the usage of `get-installedmodule az` with `get-module az -listavailable`

![image](https://user-images.githubusercontent.com/3605266/138612634-7a6647cd-4547-41ef-a853-64d08a9f7ddb.png)

![image](https://user-images.githubusercontent.com/3605266/138612658-80b70606-c079-48dd-8a2a-898d24977de4.png)

Below is the current validate dependency script/function from: `\AzDeploymentStacksPrivatePreview\AzDeploymentStacksPrivatePreview.ps1`

![image](https://user-images.githubusercontent.com/3605266/138613078-bb5433a6-01c9-4d5c-94ac-c3b5fff1ceb8.png)

It will be easy to make this more generic so that it just checks if the module is available on the system without checking actually HOW it was installed or how it became available.

instead of line 333

```powershell
$installedAzModules = Get-InstalledModule -Name Az -AllVersions -ErrorAction SilentlyContinue | Sort-Object -Descending Version
```

consider the following:

```powershell
$installedAzModules = Get-Module -Name Az -Listavailable -All | sort -Descending version | select -first 1
```

Then also replace the `get-installedmodules` on line 342

```powershell
if (!(Get-InstalledModule -Name Az -MinimumVersion 6.0 -ErrorAction SilentlyContinue)) {
```

just re-use the previous variable, which already has the latest version.

```powershell
if (!($installedAzModules.Version -gt [version]6.0.0.0)) {
```

Or something Similar. Either way remove the usage of: `Get-InstalledModule`

The AZ module is supported in both 5.1 and 7, so this would ensure it works in both of these scenarios
> The Az PowerShell module is based on the .NET Standard library and works with PowerShell 7 and later on all platforms including Windows, macOS, and Linux. It's also compatible with Windows PowerShell 5.1.

**Comment by brwilkinson** [comment]
Another consideration is that Az.Resources `4.4.0` is the latest az.resources now, so when installing az.resources via the script it installs `4.3.8` which is lower so it will not load by default?!

```powershell
find-module az.resources -AllVersions | select Name,version,PublishedDate

Name         Version PublishedDate
----         ------- -------------
Az.Resources 4.4.0   10/12/2021 6:10:57 AM
Az.Resources 4.3.1   9/7/2021 6:05:45 AM
```

```powershell
find-module az -AllVersions | select Name,version,PublishedDate

Name Version PublishedDate
---- ------- -------------
Az   6.5.0   10/12/2021 6:12:34 AM
Az   6.4.0   9/7/2021 6:07:38 AM
```

Might need to bump the module version in the package to above 4.4.0. ?

**Comment by brwilkinson** [comment]
I forgot that issue still exists in powershell 5 with `get-module az -listavailable` where az module is ignored.

https://github.com/PowerShell/PowerShell/issues/8125#issuecomment-433212351

I thought it was Arizona, however it's actually Azerbaijani.

```powershell
[CultureInfo]::GetCultureInfo('az')

LCID             Name             DisplayName
----             ----             -----------
44               az               Azerbaijani
```

which was resolved in pwsh 7.

https://github.com/PowerShell/PowerShell/pull/8142

so I think get-installedmodule is the safe option in that case. 
- So long as the install script is run in the same PowerShell/pwsh version where AZ was installed, it will work.

**Comment by brwilkinson** [comment]
otherwise, the following should work under both 5 & 7.

333
```powershell
$installedAzModules = Get-Module -Name Az.Resources -Listavailable -All | sort -Descending version | select -first 1
```

342
```powershell
if (!($installedAzModules.Version -gt [version]'3.5.0.0')) {
```

**Comment by bmoore-msft** [comment]
@stuartko - can you add a AzDO task # to link this to

**Comment by bmoore-msft** [comment]
Let's bump the version to something arbitrarily high so we don't have to argue w/ the public cmdlets during private preview.

re: PS5, I'm ok with requiring v6 or v7 during the private preview

**Comment by bmoore-msft** [comment]
@brwilkinson - I think we fixed the versioning issue - is there more you're concerned about here?

**Comment by brwilkinson** [comment]
All good here.
