### ISSUE TITLE
Deployment Stack in DeploymentStackInNonTerminalState "Deleting Resources"

### ISSUE THREAD

**Issue by h00jraq** [Azure/deployment-stacks#162]
**Describe the bug**
My deployment did not had any state for quite a while and I could not delete it either (delete option was greyed out).
IaC Pipeline was just running and running so after 35 minutes I had to cancel it. When I tried to run it again, I got below error 

`message:
ERROR: (DeploymentStackInNonTerminalState) The deployment stack resource '/subscriptions/1939665b-33e2-4667-a535-882c27133abd/resourceGroups/rg-dev-xrm-nonprod-int-1/providers/Microsoft.Resources/deploymentStacks/pdoDev' could not be updated as it is currently in a non-terminal state 'DeletingResources'.
Code: DeploymentStackInNonTerminalState
Message: The deployment stack resource '/subscriptions/1939665b-33e2-4667-a535-882c27133abd/resourceGroups/rg-dev-xrm-nonprod-int-1/providers/Microsoft.Resources/deploymentStacks/pdoDev' could not be updated as it is currently in a non-terminal state 'DeletingResources'.`

I had to wait like 10-15 minutes after pipeline cancelation to see that deployment stack has failed to delete some resources.
<img width="977" alt="image" src="https://github.com/Azure/deployment-stacks/assets/27428274/04ca2098-2118-497d-930b-71ed930a159a">

Now, when I'm trying to re-run the IaC pipeline again, I can see below screen
<img width="996" alt="image" src="https://github.com/Azure/deployment-stacks/assets/27428274/eb65ee38-9236-4446-813a-766484308cef">
Private Endpoint was created but I can't see the Network Interface and pipeline is running again for like 15 minutes...
Now, when I try to re-rub the bicep, it stuck on Private Endpoint creation:
<img width="1137" alt="image" src="https://github.com/Azure/deployment-stacks/assets/27428274/4f7c15fb-3bb1-482f-bdbe-6da7aa298cd3">

I think I know why it has failed but tbh, I'm not sure how to resolve this issue.

I believe that the problem is, Private Dns Zone is located in different RG and in different subscription which can be seen in the privateEndpoint.bicep module code, to be more specific:
```
resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' existing = {
  scope: resourceGroup(peDnsZoneSubscrId, peDnsZoneResourceGroupName)
  name: privateDnsZoneName
}
```
 and there was a resource lock Resource Group where `vnetpe` is located

I commented out below code in my main.bicep files and my first question was: Will Bicep try to remove both `vnetpe` and `subnetpe` if they were not in the deployment stack? My assumption was it will not try to delete them. 
I believe that bicep failed to remove A-records from private dns zones which are in different rg/subscription but this is client choice and not main so I'm trying to find out how I can 

Here is the command which I'm using.
Before I run deployment, I remove the lock on particular RG and re-apply it after.
In this particular case, I forgot to remove remove the lock from one of the RG so it failed to delete "something" but I can't find out what exactly...

```
az stack group create \
  --name ${{ parameters.stackName }} \
  --subscription ${{ variables.SUBSCRIPTION_ID }} \
  --resource-group ${{ variables.RG }} \
  --template-file ${{ variables.BICEP_PATH }}/${{ variables.BICEP_TEMPLATE_FILE }} \
  --parameters ${{ variables.BICEP_PATH }}/${{ variables.BICEP_PARAM_FILE }} \
  --deny-settings-mode 'none' \
  --delete-resources
```

```
resource vnetpe 'Microsoft.Network/virtualNetworks@2023-05-01' existing = {
  scope: resourceGroup(subscrId, vnetRg)
  name: vnetPE
}

resource subnetpe 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {
  name: subnetPE
  parent: vnetpe
}

module privateEndpointModuleWebApp '../../modules/privateEndpoint.bicep' = {
  name: 'pe-${peWebApp}'
  params: {
    appId: webApp.id
    location: location
    peAppName: peWebApp
    peDnsZoneResourceGroupName: peDnsZoneResourceGroupName
    peDnsZoneSubscrId: peDnsZoneSubscrId
    peSubnetId: subnetpe.id
    plServiceConnectionGroupId: 'sites'
    privateDnsZoneConfigsName: 'refMngmtApiWebAppConfig'
    privateEndpointDnsGroupName: 'webappPrivateEndpointDnsGroup'
    privateDnsZoneName: 'privatelink.azurewebsites.net'
  }
}
```

here is the privateEndpoint.bicep module code:
```
param appId string
param location string
param peAppName string
param peSubnetId string
param peDnsZoneSubscrId string
param peDnsZoneResourceGroupName string
param privateEndpointDnsGroupName string
param privateDnsZoneConfigsName string
param plServiceConnectionGroupId string
param privateDnsZoneName string

resource privateEndpoint 'Microsoft.Network/privateEndpoints@2021-05-01' = {
  name: peAppName
  location: location
  properties: {
    subnet: {
      id: peSubnetId
    }
    privateLinkServiceConnections: [
      {
        name: peAppName
        properties: {
          privateLinkServiceId: appId
          groupIds: [
            plServiceConnectionGroupId
          ]
          privateLinkServiceConnectionState: {
            status: 'Approved'
            description: 'Approved by pipeline'
          }
        }
      }
    ]
  }
}

resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' existing = {
  scope: resourceGroup(peDnsZoneSubscrId, peDnsZoneResourceGroupName)
  name: privateDnsZoneName
}

resource privateEndpointDnsGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-04-01' = {
  name: privateEndpointDnsGroupName
  parent: privateEndpoint
  properties: {
    privateDnsZoneConfigs: [
      {
        name: privateDnsZoneConfigsName
        properties: {
          privateDnsZoneId: privateDnsZone.id
        }
      }
    ]
  }
}
```

**To Reproduce**
1. Quite difficult to reproduce I'm afraid ...

**Expected behavior**
Being able to see which resource were failed to delete

**Repro Environment**
Host OS:
Powershell Version:

**Server Debugging Information**
Correlation ID: 2a2d910b-7846-4fbe-960f-b813a517ce65
Tenant ID: 7cc60758-5c35-453b-b9c2-099367865b7d
Timestamp of issue (please include time zone): CET 4/17/2024, 4:41:56 PM
Data Center (eg, West Central US, West Europe): UK-South

**Additional context**

**Comment by benemanu** [comment]
Hey @h00jraq, i have the same Issue.  Using the 'detachAll' value for the --action-on-unmanage flag seemed to resolve the Issue last time. But this time this didn't work. Do you have any other fix for this?

**Comment by carlgleisner** [comment]
Wow – I just hit this in development and testing. Would have been a nightmare in production.

@benemanu Did you manage to work around this?

I just cannot remove my deployment stack or anything.

**Comment by dantedallag** [comment]
@carlgleisner could you give us a correlation id? Would love to help figure out why it is getting stuck and assist in getting it unstuck.

**Comment by carlgleisner** [comment]
@dantedallag Many thanks for asking!

I'm sorry to say that I prior to noting your message had managed to finally tear all the resources down to start from scratch. I'm still in an exploratory phase luckily.

Again, many thanks 🙂

**Comment by RCSandberg** [comment]
I've got the same issue. Here's the correlation ID related to this: c361b396-f502-4577-a1e5-cbc4de14a35d

Using detachAll did nothing to help.

Update: Using the CLI to list the stacks and checking what the "provisioningState" is revealed that it was stuck in "deletingResources", for quite some time, even though all seemed fine in the portal. And by quite some time, I'd say 30-45 minutes. After this time the state was instead "failed" and redeploying the stack was possible to try again. However, the end result was still not successful and the provisioningState revealed it was stuck again.

**Comment by dantedallag** [comment]
@RCSandberg I'm having trouble finding an operation associated with the correlation id you provided. Could you double check that it is correct?

Also, 30-45 minutes is not an unprecedented amount of time for a deletion to occur. Some resources take quite a while to fully delete. What sorts of resources were you deleting within the stack?

**Comment by RCSandberg** [comment]
Hi @dantedallag,
I was a bit quick to judge that it was possible to redeploy successfully again. It got stuck again with some failure state which I no longer remember.

Not sure what it was trying to delete. I ran a what-if with a regular deployment command before, which said something like 7 to ignore and 5 no change. But I suspect that it was possibly a storage account or a function app.

Using other means to delete these resources rarely takes more than a couple of minutes, at most.

The correlation ID was correct. Cannot find it anymore in the deployments page under the resource group since only 19 rows are visible there. But location is West Europe, if that helps.

I got fed up with waiting for the stack and instead went back to regular az deployment.

**Comment by abhisheik-HRA** [comment]
I am facing same issue - the deployment stack just gets stuck in deleting resources state and takes more than 45 mins to fail.

**Comment by riosengineer** [comment]
This is still quite common when you use stacks with the same name and recreate frequently. It takes less than 45 mins to fail for me, but still 15/20 mins of wasted time.

@dantedallag @azcloudfarmer 

```
Error: Request failed. CorrelationId: 5d815f27-2a44-472b-8f82-bfabdf901b04
Error: {
  "code": "DeploymentStackInNonTerminalState",
  "message": "The deployment stack resource '/subscriptions/***/providers/Microsoft.Resources/deploymentStacks/app-stack-pr-3' could not be updated as it is currently in a non-terminal state 'Deleting'."
}
Error: Create failed
```
