### ISSUE TITLE
What is in GA for Az PS modules of deployment stack

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#166]
**Is your feature request related to a problem? Please describe.**
Az 12.0 was released https://github.com/Azure/azure-powershell/releases/tag/v12.0.0-May2024?utm_source=pocket_saves with release note: Deployment Stack cmdlets GA release/updates.
but it does not says if there are any changes/updates or it is just bug fixes,
Can you clarify?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aperezmicrosoft** [comment]
Hi @slavizh - details on the GA release here: https://github.com/Azure/deployment-stacks/releases/tag/v0.2.1

**Comment by slavizh** [comment]
Thanks!
