### ISSUE TITLE
Implement Terraform "prevent_destroy"

### ISSUE THREAD

**Issue by pawelpabich** [Azure/deployment-stacks#171]
**Is your feature request related to a problem? Please describe.**
I want to ensure that Bicep, no matter what mode it is running in, never deletes certain resources.  Resource locks don't achieve this goal as often they are created using Bicep itself.  

**Describe the solution you'd like**
Something close to [Terraform "prevent_destroy" ](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle)that is specified on the resource itself would be perfect.

**Comment by dantedallag** [comment]
Hey @pawelpabich, I'm trying to understand your ask a little better. Could you give an example of how Deny Assignments in Deployment Stacks don't solve this issue?

**Comment by dantedallag** [comment]
Hi @pawelpabich, I realized after I made my first comment that you originally posted this in the Bicep repo and it was transferred here. So, if you are unsure about Deployment Stacks or Deny Assignments as I referenced in my last comment, you can take a look here: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deployment-stacks?tabs=azure-powershell.

It would still be great to get an example workflow of what you would like to see though. This will help me better understand if the support exists already or if this requires further work.

**Comment by dantedallag** [comment]
@pawelpabich If you are still facing issues, please provide a more detailed description of current behavior and the behavior you would like to see.

**Comment by pawelpabich** [comment]
Hey, sorry, I missed your first message. It does look like deployment stacks will solve this problem for me. I'm assuming that leaving `DenySettingsExcludedPrincipal` list empty will prevent anybody from deleting a resource. Is that correct?

**Comment by dantedallag** [comment]
Yeah, `DenySettingsExcludedPrincipal` allows specification of principals that can get around the deny assignments.

I'm glad that deployment stacks seem to be a solution to your problem. For future readers of this comment, I want to be clear that deployment stacks deny assignment workflow and terraform "prevent_destroy" are not exactly the same and I encourage reading through our documentation to understand our features/limitations.

Please let us know if you have any questions or asks for improvement!
