### ISSUE TITLE
"validate" command is missing in Az PowerShell

### ISSUE THREAD

**Issue by J0F3** [Azure/deployment-stacks#172]
**Describe the bug**
In the Azure CLI there are command to validate a deployment stack. (az stack group validate, az stack sub validate, az stack mg validate). But in Azure PowerShell there are no equivalent Cmdlets. 

**To Reproduce**
1. Try to validate a deployment Stack in PowerShell. 

**Expected behavior**
For every command in the Azure CLI there is also an equivalent Cmdlet in the Azure PowerShell.

**Screenshots**
![image](https://github.com/Azure/deployment-stacks/assets/12759579/f3de0cde-89ed-4de4-bfdf-22965d94980b)

**Repro Environment**
Host OS: Linux / Windows
PowerShell Version: 7.4.3, 7.1.0 Az Module

**Server Debugging Information**
N/A

**Additional context**
N/A

**Comment by dantedallag** [comment]
Hey @J0F3, we are aware and are implementing this. We can keep this issue to track.

**Comment by J0F3** [comment]
Hey @dantedallag Cool. Thank you!  
I was quite surprised that there is no validate command in PowerShell and did not found anything about it. So I thought I just open an issue to get it clarified.... 🙂

**Comment by dantedallag** [comment]
@J0F3 This should be available now if you update the cmdlets. Let us know if you run into any issues!
