### ISSUE TITLE
Use DenyAssignments to restrict read access to specific container

### ISSUE THREAD

**Issue by zyzzler** [Azure/deployment-stacks#176]
I have already posted my question at "learn.microsoft.com". However, I guess the expertise to solve this issue can rather be found here. I hope it is okay, if I just post the link to my question here:

https://learn.microsoft.com/en-us/answers/questions/1806091/use-denyassignments-via-deployment-stack-to-restri

If you have any suggestion on how to solve this I would greatly appreciate it! Thank you very much in advance and please let me know if you need any further input from my side. Thanks a lot!

**Comment by slavizh** [comment]
Hi,
Answer was provided to you in the Q&A thread. In short stacks is not intended for the capabilities you are looking for.
