### ISSUE TITLE
Deployment Stack resource could not be updated as it is currently in a non-terminal state 'Initializing'.

### ISSUE THREAD

**Issue by mr-sa-enc** [Azure/deployment-stacks#180]
**Describe the bug**

I was running some local tests and I deployed two Deployment Stacks: one at Subscription Scope and another at Resource Group Scope. After few minutes, I realized that something went wrong. In both cases the process never finished because they were stuck in 'Initializing' state. 

I tried to check if the Azure CLI had the command 'wait' for Deployment Stack available like the other services but it hasn't been added yet.

**To Reproduce**

I haven't found a way to reproduce it. However, I used the command `az monitor activity-log list --correlation-id` to get a better idea about the issue. The response was: 

`"message": "Microsoft.Resources/deploymentStacks/write","statusCode": "GatewayTimeout","statusMessage": "{\"error\":{\"code\":\"GatewayTimeout\",\"message\":\"The gateway did not receive a response from 'Microsoft.Resources' within the specified time period.\"}}`

`Code: DeploymentStackInNonTerminalState`

**Screenshots**

![image](https://github.com/user-attachments/assets/978d830a-7f1b-49e2-a836-1f2aba1a254c)

Finally, after more than 20 hours the status is the same. I'd really appreciate if you can guide me.

**Comment by dantedallag** [comment]
Hi @mr-sa-enc, could you share the correlation id so that we can look into what is happening?

**Comment by mr-sa-enc** [comment]
Hi @dantedallag, thanks for your response. 

Regarding the Correlation Id, I still need an approval from my manager to share it... due to our internal processes.

Meanwhile, If we need support with the DS, What is the correct channel to use?

**Comment by dantedallag** [comment]
If you would prefer not to post information here, feel free to send information to ARMDeploymentStacks@microsoft.com or you can create a formal support request through Azure support. We cannot really help until we can identify the stack that is having issues and a correlation id is normally the easiest way.

**Comment by mr-sa-enc** [comment]
Hi @dantedallag, I already sent the mail with the Correlations IDs.

**Comment by dantedallag** [comment]
Cleaned up stuck stacks. Problem was related to a transient issue in the region.
