### ISSUE TITLE
Deployment stack failing to delete "Rule Collection Group" when unmanaged (Apiversion 2020-04-01 is not supported for Rule Collection Group xyz. Minimum API version supported is 2020-05-01)

### ISSUE THREAD

**Issue by tomcperry** [Azure/deployment-stacks#182]
**Describe the bug**
When a "rule collection group" is removed from a bicep template in a deployment stack that is configured to "delete all" when a resource becomes unmanaged, the deployment stack fails to delete the rule collection group.
After some time in state "deletingResources", the deployment stack goes into a failed state, with the failed resources contain the following error: 

```json
[
    {
        "error": {
            "code": "FirewallPolicyRuleCollectionGroupApiNotSupported",
            "message": "Apiversion 2020-04-01 is not supported for Rule Collection Group rcg-webserver. Minimum API version supported is 2020-05-01"
        },
        "id": "/subscriptions/..../resourceGroups/rg-fw-policy-demo/providers/Microsoft.Network/firewallPolicies/fwpol-demo/ruleCollectionGroups/rcg-webserver"
    }
]
```

**To Reproduce**

Manually create an Azure Firewall Policy resource in a resource group and note the names.  

Create the following bicep templates:

`main.bicep`:
```bicep
targetScope = 'subscription'

param fwPolicyName string
param rgName string
param ruleCollectionGroupNames string[]

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' existing = {
  name: rgName
}

module fwPolicy 'fwpolicy.bicep' = {
  name: 'fwpolicy'
  scope: resourceGroup(rg.name)
  params: {
    fwPolicyName: fwPolicyName
    ruleCollectionGroupNames: ruleCollectionGroupNames
  }
}

```

`fwpolicy.bicep`:
```bicep
targetScope = 'resourceGroup'

param fwPolicyName string

param ruleCollectionGroupNames string[]

resource fwPolicy 'Microsoft.Network/firewallPolicies@2020-11-01' existing = {
  name: fwPolicyName
}

@batchSize(1)
resource ruleCollectionGroups 'Microsoft.Network/firewallPolicies/ruleCollectionGroups@2024-01-01' = [
  for (rcgName, i) in ruleCollectionGroupNames: {
    name: rcgName
    parent: fwPolicy
    properties: {
      priority: 100 + (i * 10)
      ruleCollections: [
        {
          ruleCollectionType: 'FirewallPolicyFilterRuleCollection'
          priority: 100
          name: 'rc-demo-${i}'
          action: {
            type: 'Allow'
          }
          rules: [
            {
              ruleType: 'NetworkRule'
              name: 'demo-rule-${i}'
              sourceAddresses: ['10.0.0.1']
              destinationAddresses: ['10.0.0.2']
              ipProtocols: ['TCP']
              destinationPorts: ['80']
            }
          ]
        }
      ]
    }
  }
]
```

Create the following bicep parameter files (with the names of the existing firewall policy and resource group):

`original.bicepparam`:
```bicep
using 'main.bicep'

param fwPolicyName = 'fwpol-demo'
param rgName = 'rg-fw-policy-demo'

param ruleCollectionGroupNames = [
  'rcg-application'
  'rcg-database'
  'rcg-webserver'
]
```

`after.bicepparam`:
```bicep
using 'main.bicep'

param fwPolicyName = 'fwpol-demo'
param rgName = 'rg-fw-policy-demo'

param ruleCollectionGroupNames = [
  'rcg-application'
  'rcg-database'
]
```
**Note that only the difference in the parameter files is that one group name has been removed**

Set the following variables:

```bash
PRINCIPAL_OBJECT_ID='...' # Unsure if this is required, but it is in my failing example - set to own user object ID for demo
SUBSCRIPTION_ID='...' # Subscription ID where the deployment will be made (same sub as the firewall policy created before)
LOCATION='westeurope' # I have only tested with West Europe
TEMPLATE_FILE='main.bicep' 
STACK_NAME='firewall-policy-stack' # Can be anything
```

Create the deployment stack using the `original.bicepparam` parameter file. This will deploy 3 new rule collection groups to the existing firewall policy:

```bash
az stack sub create \
  --name "$STACK_NAME" \
  --location "$LOCATION" \
  --subscription "$SUBSCRIPTION_ID" \
  --deny-settings-mode denyWriteAndDelete \
  --action-on-unmanage deleteAll \
  --template-file "$TEMPLATE_FILE" \
  --parameters original.bicepparam \
  --deny-settings-excluded-principals "$PRINCIPAL_OBJECT_ID" \
  --no-wait \
  --yes
```

Wait for deployment to succeed, then redeploy with `after.bicepparam`. This has one rule collection group definition removed:

```bash
az stack sub create \
  --name "$STACK_NAME" \
  --location "$LOCATION" \
  --subscription "$SUBSCRIPTION_ID" \
  --deny-settings-mode denyWriteAndDelete \
  --action-on-unmanage deleteAll \
  --template-file "$TEMPLATE_FILE" \
  --parameters after.bicepparam \
  --deny-settings-excluded-principals "$PRINCIPAL_OBJECT_ID" \
  --no-wait \
  --yes
```

Note that the second deployment succeeds, but then when the deployment stack moves into the "deletingResources" state, it gets stuck for several minutes.  
After approx. 20-50 minutes, the stack goes into a "failed" state.

**Expected behavior**  
The deployment stack is attempting to follow expected behaviour, as it is attempting to delete the unmanaged resource.  
However, the expected behaviour would be that the deletion succeeds in a short period of time, and then the deployment stacks moves into a "succeeded" state.

**Repro Environment**  
Host OS: Ubuntu 22.04.4 LTS running in WSL on Windows 11  

```
$ az version 
{
  "azure-cli": "2.62.0",
  "azure-cli-core": "2.62.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "bastion": "0.3.0",
    "reservation": "0.3.1",
    "ssh": "2.0.3",
    "virtual-wan": "1.0.0"
  }
}

$ az bicep version 
Bicep CLI version 0.29.47 (132ade51bc)
```

**Server Debugging Information**  
Correlation ID: ae3b7f84-c505-41db-8bd9-eb393ac011e5  

Raw Error:
```json
{
  "code": "DeploymentStackDeleteResourcesFailed",
  "message": "One or more resources could not be deleted. Correlation id: 'ae3b7f84-c505-41db-8bd9-eb393ac011e5'.",
  "details": [
    {
      "code": "DeploymentStackDeleteResourcesFailed",
      "message": "An error occurred while deleting resources. These resources are still present in the stack but can be deleted manually. Please see the FailedResources property for specific error information. Deletion failures that are known limitations are documented here: https://aka.ms/DeploymentStacksKnownLimitations"
    }
  ]
}
```

Tenant ID: 2e114308-14ec-4d77-b610-490324fa1844  

Timestamp of issue (please include time zone): 07/08/2024, 12:46:59 CEST (UTC+2)  

Data Center (eg, West Central US, West Europe): West Europe

**Comment by tomcperry** [comment]
Hi @azcloudfarmer, 
I realised that my example above is overly complicated as I just replicated what I am doing in our real scenario (eg, including denySettings, including existing resources, subscription deployment stack etc). 
So I made the most simple example possible to show the issue directly. 

Here I am just making a resource group-scoped deployment stack on an existing resource group. The template contains the firewall policy and two empty rule collection groups. The only important flag I am using is `--action-on-unmanage deleteAll`
This deploys successfully, and the two rule collection groups get created as expected. 
Then I remove the 2nd rule collection group from the template and redeploy. I would expect the removed rule collection group to be deleted, but it behaves as before where the deployment completes fast, but then deployment stack gets stuck in status "deletingResources" before eventually failing with the same error: 

```json
[
    {
        "error": {
            "code": "FirewallPolicyRuleCollectionGroupApiNotSupported",
            "message": "Apiversion 2020-04-01 is not supported for Rule Collection Group rcg02. Minimum API version supported is 2020-05-01"
        },
        "id": "/subscriptions/41640fc2-0ff7-4135-aea7-54c11e1d3b76/resourceGroups/rg-fwpolicy-simple/providers/Microsoft.Network/firewallPolicies/demo-fw-policy/ruleCollectionGroups/rcg02"
    }
]
```

The template I am using is this:
`demo.bicep`:
```bicep
targetScope = 'resourceGroup'

resource fwpolicy 'Microsoft.Network/firewallPolicies@2024-01-01' = {
  name: 'demo-fw-policy'
  location: resourceGroup().location
  properties: {
    sku: {
      tier: 'Standard'
    }
  }
}

resource rcg01 'Microsoft.Network/firewallPolicies/ruleCollectionGroups@2024-01-01' = {
  name: 'rcg01'
  parent: fwpolicy
  properties: {
    priority: 100
    ruleCollections: []
  }
}

resource rcg02 'Microsoft.Network/firewallPolicies/ruleCollectionGroups@2024-01-01' = {
  name: 'rcg02'
  parent: fwpolicy
  dependsOn: [
    rcg01
  ]
  properties: {
    priority: 200
    ruleCollections: []
  }
}
```

I deploy with this (assuming `$RG_NAME` is already set): 
```bash
az stack group create \
   --action-on-unmanage deleteAll \
   --deny-settings-mode none \
   --name fw-policy-simple \
   --resource-group $RG_NAME \
   --template-file demo.bicep
```

After successful completion, I adjust the template as follows: 

`demo.bicep`:
```bicep
targetScope = 'resourceGroup'

resource fwpolicy 'Microsoft.Network/firewallPolicies@2024-01-01' = {
  name: 'demo-fw-policy'
  location: resourceGroup().location
  properties: {
    sku: {
      tier: 'Standard'
    }
  }
}

resource rcg01 'Microsoft.Network/firewallPolicies/ruleCollectionGroups@2024-01-01' = {
  name: 'rcg01'
  parent: fwpolicy
  properties: {
    priority: 100
    ruleCollections: []
  }
}
```

I re-run the `az stack` command above and the deployment finishes very fast. But the deployment stack fails with the following errors; 

```json
[
    {
        "error": {
            "code": "FirewallPolicyRuleCollectionGroupApiNotSupported",
            "message": "Apiversion 2020-04-01 is not supported for Rule Collection Group rcg02. Minimum API version supported is 2020-05-01"
        },
        "id": "/subscriptions/41640fc2-0ff7-4135-aea7-54c11e1d3b76/resourceGroups/rg-fwpolicy-simple/providers/Microsoft.Network/firewallPolicies/demo-fw-policy/ruleCollectionGroups/rcg02"
    }
]
```

The correlation ID for this error is: `b8ceeacc-8257-4ec2-aa58-ebdecb1399ab`

The only other thing to mention is that in the original template that contains the two rule collection groups, I need to make the 2nd group depend on the 1st, as otherwise I get an error that the firewall policy is already in updating state.

**Comment by aperezmicrosoft** [comment]
Hello @tomcperry - thank you for the updated details. We are investigating this issue and will get back to you as soon as possible. Thanks!

**Comment by Pranshu258** [comment]
We have made a change that should fix this issue. It will be part of the next ARM (Azure Resource Manager) release. We update here once the fix is deployed.

**Comment by dani3lh3pe** [comment]
@Pranshu258, want to remove a rule collection group and get the same error like @tomcperry.
Do you have any update about ETA of the fix?

Thank you!

**Comment by aperezmicrosoft** [comment]
Hi @dani3lheidemann - this fix should be fully deployed now. Can you please double check on your end? Thanks! @Pranshu258 as cc

**Comment by snarkywolverine** [comment]
Hi @dani3lheidemann - I'm closing this, since this has been fixed. If you see the issue again, please feel free to re-open the issue. Thanks!
