### ISSUE TITLE
Creating a deployment stack from Portal does nothing

### ISSUE THREAD

**Issue by stpatrick2016** [Azure/deployment-stacks#189]
**Describe the bug**
When creating a deployment stack from the portal, after clicking Create, nothing happens, the stack creation page just closes and no deployment is initiated.
Please note - this worked fine last time on September 3rd, 2024 (didn't test after that, last week, it was reported to have stopped working).

**To Reproduce**
Listing full steps from the portal, though shortcuts are possible (like having a template link in the URL)
1. Go to https://portal.azure.com/#create/Microsoft.Template
2. Click on Edit template and add any resource (I added a storage account)
3. Click Save
4. You will see a suggestion to use the new Deployment Stacks instead of deployment
5. Follow the suggestion and click on it
6. Edit the template again and again add the resource
7. Click on Save
8. Under "Create In" select "Resource Group"
9. Supply the name of the deployment stack ("Test1" for example)
10. Click on Next
11. Select any resource group (or create a new one)
12. Click Review and Create

**Expected behavior**
The deployment stack is validated and created, and the deployment begins

**Additional context**
Checking in dev tools in browser (Chrome), no errors and I see no data being sent to server at all

**Comment by snarkywolverine** [comment]
@stpatrick2016 - Thanks for reporting this! We're actively working on a fix. We'll keep you updated on the timeline with the fix.

**Comment by snarkywolverine** [comment]
This has been fixed - thanks for reporting it!
