### ISSUE TITLE
Referencing a keyvault secret in a bicep template will result in an attempted delete of that secret on unmanage

### ISSUE THREAD

**Issue by mligtenberg** [Azure/deployment-stacks#191]
**Describe the bug**
Given a template were a keyVault secret is referenced via ``keyVault.getSecret('x')``
When trying to create a new deployment where the secret is no longer referenced with `--action-on-unmanage "deleteResources"`
The deployment stack will attempt to delete the referenced secrets (and fail if the principal does not have delete permissions)

**To Reproduce**
Given the following template:
Using https://github.com/Azure-Samples/azd-starter-bicep as a base
1. in the root create a bicep file with the following contents
```bicep
param keyvaultName string
param secretName string

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: keyvaultName
}

module sqlServer './infra/core/database/sqlserver/sqlserver.bicep' = {
  name: '${deployment().name}-sqlServer'
  params: {
    location: location.name
    tags: tags
    name: 'dps-kv-reference-bug-test'
    databaseName: 'testdb'
    keyVaultName: keyVault.name
    appUserPassword: keyVault.getSecret('sql-user-password')
    sqlAdminPassword: keyVault.getSecret('sql-admin-password')
  }
}
```

2. Deploy the bicep in a deployment stack
3. comment out the sql module
4. Redeploy bicep with ``--action-on-unmanage "deleteResources"``

The deployment stack will attempt to delete the referenced secrets (and fail if the principal does not have delete permissions)

**Expected behavior**
When doing the second deployment I would expect that the deployment stack would not try to delete referenced secrets

**Screenshots**

**Repro Environment**
Host OS: Linux Ubuntu 22.04 (azure devops hosted agent)
Azure CLI Version: 2.65.0

**Server Debugging Information**
Correlation ID: 40fc9386-27e8-4668-a005-743231e42f03
Tenant ID:
Timestamp of issue (please include time zone): 2024-10-21T09:56:23Z
Data Center (eg, West Central US, West Europe): West Europe

**Additional context**

**Comment by aperezmicrosoft** [comment]
Hi @mligtenberg - this is a known issue/limitation from Key Vaults today. First seen here #142. We are working on a fix to be able to succeed the deployment stack when these non-deletable resources are encountered. In the meantime, our recommendation is to first remove the secrets from the KV and then attempt the Deployment Stack delete.

**Comment by mligtenberg** [comment]
Hi @azcloudfarmer I think that this issue is distinct from #142. I'm not creating secrets in my stack.
I'm simply raising a reference to a secret.

Just like the fact that a resource with the ``existing`` keyword does not get into a deployment stack,
for example
```bicep
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: keyvaultName
}
```

I would expect that a ``keyVault.getSecret('sql-user-password')`` would als not add the secret to the stack. This would translate to the following in arm:

```json
"appUserPassword": {
    "reference": {
        "keyVault": {
            "id": "[resourceId('Microsoft.KeyVault/vaults', keyvaultName)]"
        },
        "secretName": "permissions-sql-user-password"
    }
}
```

So I think I should rephrase the bug:  
When referencing a exsiting keyvault secret, it gets mistakenly added to the tracked resources.

**Comment by mligtenberg** [comment]
Nevermind, I feel really dumb right now. I see now that the template I've been using creates a new secret (which it shouldn't).
Thanks for looking into it. I will close this issue.
