### ISSUE TITLE
Ability to do -Verbose and to show progress like New-AzDeployment -Verbose

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#20]
**Is your feature request related to a problem? Please describe.**
Ability to do -Verbose and to show progress like New-AzDeployment -Verbose
Allows for following live progress when ran in pipeline.

**Describe the solution you'd like**
Ability to do -Verbose and to show progress like New-AzDeployment -Verbose

**Describe alternatives you've considered**
I do not see alternatives.

**Comment by slavizh** [comment]
Also verbose should show deleting resources progress. When there is some delete process it seems that deployment takes way longer, especially when there is some deletion failure.

**Comment by rbnmk** [comment]
I would like to add to this that this would be helpful. I always use the -Verbose switch in Azure DevOps pipelines to output information about 'what is going on'.

**Comment by aperezmicrosoft** [comment]
Verbose support is available in Deployment Stacks. Please follow https://github.com/Azure/deployment-stacks/issues/107 for updates on verbose support for delete operations of the Stack
