### ISSUE TITLE
Question about New-AzSubscriptionDeploymentStack  usage

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#22]
Instead of using New-AzSubscriptionDeploymentStack and after it Set-AzSubscriptionDeploymentStack can I use only New-AzSubscriptionDeploymentStack all the time? Is there any difference if I use New-AzSubscriptionDeploymentStack instead of Set-AzSubscriptionDeploymentStack  on existing stack?

**Comment by bmoore-msft** [comment]
No difference - PowerShell has a "standard" that everyone have a "Set" cmdlet.

**Comment by slavizh** [comment]
Thanks! That is great!
