### ISSUE TITLE
Subscription-scoped Deployments not visible

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#23]
**Describe the bug**
Yesterday I was doing some testing of one deployment stack and today I am doing with another one. Under Deployments for the subscription I can only see the deployment stacks deployments from yesterday by not today. Is this some issue particularly to Deployment stacks or not related to it?

![image](https://user-images.githubusercontent.com/11890856/139420506-8e6c8088-a461-413d-a2aa-f6fd86c65994.png)

**Comment by bmoore-msft** [comment]
I don't think related to stacks, likely a replication delay - do you see them today?  Also if you run `Get-AzSubscriptionDeployment` does it return them?  Or `Get-AzSubscriptionDeployment -Name $(get this from the stack)`?

**Comment by slavizh** [comment]
Get-AzSubscriptionDeployment didn't return them. When I started to deploy a new stack (third one) I saw a few of them appear for the previous stack (the second one) but those for the current stack were also missing.
When I did manual deployment via New-AzDeployment appeared right away.

**Comment by bmoore-msft** [comment]
There have been issues with replication of late - would like to get a feel for other folks also experiencing this...

**Comment by slavizh** [comment]
It is very annoying as when you have something failed it is hard to troubleshoot as you do not see what is the deployment error until the deployment starts to appear which takes a lot of time.

**Comment by bmoore-msft** [comment]
Once W5 gets deployed we should re-test this...

**Comment by bmoore-msft** [comment]
2 things on this one...
1) we are still seeing some replication delays for sub scoped deployments - the ETA for this is EOY but take that prediction with the context of lifetime of this issue
2) to get around it in the short term, create the sub scoped stack in the region where you're sitting - the deployment gets created in that same location and your next query for the deployment *should* also go to that location.  So no replication needed in that case.  How do you know where ARM thinks you're sitting?  You can use the `--debug` switch in PS/CLI and look for the `x-ms-routing-request-id` header value.  The first part is the location/region.  It will be something like this:
```
'x-ms-routing-request-id': 'CENTRALUS:20221110T170839Z:0f575eac-afaa-47c0-8983-a169c325a030'
```
So in my case I need to create subscription scoped stacks in `centralus` - note the resources created by the stack can be anywhere.

Also note that you really only have to do that once to find your location (if you don't already know) if you don't move around a lot.

Final caveat, the above is not 100% foolproof, you can still get occasionally bounced to other regions (I end up in northcentralus sometimes and on occasion canada) but this will help while we get the issue resolved.

Hopefully soon...
