### ISSUE TITLE
Delete all stacks at the end of private preview

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/deployment-stacks#27]
Once encryption work is done, previously created stacks will need to be deleted since they will not be encypted.

AzDO #10944400

**Comment by miqm** [comment]
Can we get a heads-up before stacks will be deleted? Just in case to not get the resources deleted.

**Comment by bmoore-msft** [comment]
Will confirm, I don't think we'll need this any more, though may want it since the api has changed a bit.  In any case, if we end up doing it on the backend (we may have you initiate) we will detach the resources, not purge them.

**Comment by aperezmicrosoft** [comment]
Hi @miqm - full encryption parameters are supported and no longer an issue. We recommend recreating all stacks since Private Preview if you made use of Secure Parameters.
