### ISSUE TITLE
Question: Will purging/deleting the resource group be part of deployment stacks

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#37]
As far as I understood currently if you delete deployment stack or remove resource group from deployment stacks the resources groups will not be deleted/purged. Will such functionality be part of future release? Will there be option to not purge the resource group in case there are some other resources left that were not part of the stack?

**Comment by bmoore-msft** [comment]
Current thinking is that we would delete the RG only if it's empty...  We would not delete subscriptions or managementGroups even if empty.

**Comment by bmoore-msft** [comment]
The next release will issue a DELETE call for the RG/MG if so instructed ( see #59 ).  This is equivalent to any other RG delete call so it will instruct ARM to delete the RG even if it's not empty.
