### ISSUE TITLE
template-with-stack.json contins non-working property deploymentScope

### ISSUE THREAD

**Issue by henrybeen** [Azure/deployment-stacks#41]
**Describe the bug**
The [template-with-stack.json](https://github.com/Azure/deployment-stacks/blob/main/test-templates/template-with-stack.json) template in this repo does not deploy as-is. Only by removing the deploymentScope property and adding a location property, I could get the template to deploy.

**To Reproduce**
1. Try to deploy the template as is

**Expected behavior**
- Either an update to the example, or the property deploymentScope to be accepted as defined now.
- Add location to example template

**Comment by bmoore-msft** [comment]
Thanks Henry - I think we had that up there before we got templates working... I submitted a fix.
