### ISSUE TITLE
When deploying a deployment stack from a template, the resource doesn't show in the 'deployments' blade for a while

### ISSUE THREAD

**Issue by henrybeen** [Azure/deployment-stacks#42]
When deploying a deployment stack from a template, the resource doesn't show in the 'deployments' blade for "a while"

**To Reproduce**
1. Fix the [template-with-stack.json](https://github.com/Azure/deployment-stacks/blob/main/test-templates/template-with-stack.json) template as described in #41
2. Deploy the template
3. Navigate to the target resource scope
4. Navigate to the 'deployment blade
5. Observe that the deployment stack resource is not there
6. Wait "some time"
7. Refresh the page
8. Observe that the deployment stack resource is now shown

**Expected behavior**
See the completed deployment, with the deployment stack there

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/19696205/144112690-958b7caf-8243-4920-b994-562295ba1070.png)

For reference the correlation Id: d04814f5-1586-4568-bc47-22a809814bc1 (because no developer should ever let another developer manual type over a correlation id from a screenshot)

**Comment by snarkywolverine** [comment]
Thanks for sharing the correlation ID.  Based on the logs, this was a stack created at subscription scope.  This issue is being tracked by #23.
