### ISSUE TITLE
Distribute CLI components for install with `az extension add`

### ISSUE THREAD

**Issue by damienpontifex** [Azure/deployment-stacks#56]
**Is your feature request related to a problem? Please describe.**
The releases now contain a package for use with the `az` CLI, but packaged with an MSI for windows and also has the python source as a zip inside the release artifacts. This makes it different than how other CLI beta usages are distributed e.g. https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list where I've used the aks-preview before to get new preview features into the CLI in a consistent way

**Describe the solution you'd like**
The CLI components be distributed as an `az` CLI extension. Looking at `az cli extension add -h` this could be a python wheel if not wanting to and publish it on the official microsoft extensions list yet. But if distributed this way, then a consistent cross platform approach could be used to add it to the az CLI.

**Describe alternatives you've considered**
* Publish extension to official [Microsoft page](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list)
* Publish wheel in GitHub release artifacts so the az CLI can install extension that way

**Additional context**
nil

**Comment by bmoore-msft** [comment]
I think this is going to be a "point in time" issue for us... we want to be in the base cli (not out of band as an extension) as it's a simpler install experience once we get there - at that point we'll be consistent across platforms, though I might poke on unifying the install experience prior to then.  I don't think we're going to have many releases between now and when we get in the base cli.

Can you expand on this?

> Publish wheel in GitHub release artifacts so the az CLI can install extension that way

That doesn't sound familiar to me...

**Comment by damienpontifex** [comment]
All good, thanks
