### ISSUE TITLE
CLI for Non-Windows Platform (macOS and Linux)

### ISSUE THREAD

**Issue by yks0000** [Azure/deployment-stacks#63]
**Is your feature request related to a problem? Please describe.**
Deployment Stack CLI is not available for platform other than Windows. This restrict us from testing (preview) version of deployment-stack.

**Describe the solution you'd like**
As a macOS user, I would like to see deployment stack cli build for macOS and Linux platform.

**Describe alternatives you've considered**
There is no alternative to this request.

**Comment by J0F3** [comment]
I have been using the PowerShell Cmdlets successfully on macOS. Should also work on Linux.
Just install the cross platform[PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2)  and you are basically ready to go.

Maybe this helps until the CLI is available on other platforms which I assume will be certainly the case sometime prior GA or even  public preview.

**Comment by yks0000** [comment]
Thanks @J0F3. Will try using PowerShell Cmdlets. Closing this.
