### ISSUE TITLE
No warning/error when resources are overwritten with deployment stacks

### ISSUE THREAD

**Issue by linasendriukaitis** [Azure/deployment-stacks#67]
**Is your feature request related to a problem? Please describe.**
When a resource has been changed by a 3rd party source (pipeline, PowerShell, Portal, etc.) there is no warning that the changes will be overwritten when re-running the Set-AzSubscriptionDeploymentStack command

**Describe the solution you'd like**
I would like to have a solution that allows me to specify the behavior and have the ability to receive a list of discrepancies between the code base and the actual state of the resources

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by slavizh** [comment]
Such kind of feature is already present although not perfect: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-what-if?tabs=azure-powershell

It is just not implemented on the commandlets yet.

**Comment by bmoore-msft** [comment]
@slavizh has it right, we'll have /what-if implemented in the public preview release...
