### ISSUE TITLE
Implicitly created resources are not deleted / locked by the stack [ list what you find here ]

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/deployment-stacks#70]
Inspired by #28 

There are resources in Azure that will automatically create other resources.  So in a template (which defines the stack) you will not see resources like OS disks on a VM explicitly defined because they are automatically created by the VM.  Since it is not defined in the template, the stack does not delete that resource if requested.  (stack will also not put a denyAssignment on the resource).

The VM resource declaration has a property `deleteOption` to allow the VM to clean up resources it uses/creates and the stack honor, that native capability (instead of deleting something you may have wanted to save).

If you find other resources that create resources please add them to a list here, so we can start to track these and determine the correct "native" behavior.

**Comment by aperezmicrosoft** [comment]
If anyone is running into this, please open a new GitHub issue with details on the scenario.
