### ISSUE TITLE
Bicep examples?

### ISSUE THREAD

**Issue by JustenKennedy** [Azure/deployment-stacks#71]
In the tutorial it references an arm template and whatnot. Can this also be ran with bicep files? If so, do you have an operational example? I've got everything installed correctly I believe. Just running into errors trying to run a New-AzSubscriptionDeploymentStack and my guess is I'm trying to use a main.bicep file and a bicepconfig.json file and it's not setup to use that.

**Comment by jikuja** [comment]
If preview tooling does not support bicep directly then one option you could try is to build bicep to ARM template and deploy that.

**Comment by alex-frankel** [comment]
The next release will include support for bicep files (matching the `*-Az*Deployment` and `az deployment *` commands).

**Comment by JustenKennedy** [comment]
Awesome. Do we have a time frame/ eta on the next release?

**Comment by alex-frankel** [comment]
@apclouds / @bmoore-msft can provide the most specific ETA

**Comment by bmoore-msft** [comment]
@JustenKennedy - ping again at the end of the week if you don't hear back...

**Comment by JustenKennedy** [comment]
Any update on this? @bmoore-msft

**Comment by bmoore-msft** [comment]
We're in the process of deploying the build with the new apiVersion...  trying to sneak in an out of lockdowns for the world cup, black friday/cyber monday and the end of year holidays...

**Comment by slavizh** [comment]
lol. First time I hear that there are lockdowns due to the world cup as well. Good to know.

**Comment by bmoore-msft** [comment]
Well that one only happens every 4 years ;)

**Comment by aperezmicrosoft** [comment]
The new tutorial uses Bicep to create Deployment Stacks.
