### ISSUE TITLE
Usage of  -DeleteResourceGroups -DeleteResources -DeleteAll

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#82]
**Is your feature request related to a problem? Please describe.**
With New-Az*DeploymentStack cmdlets you can specify parameters -DeleteResourceGroups -DeleteResources and -DeleteAll at the same time but isn't it irrelevant to specify -DeleteResourceGroups -DeleteResources  if you have specified -DeleteAll? Also if you have specified -DeleteResourceGroups or -DeleteResources why it is possible to specify -DeleteAll?

**Describe the solution you'd like**
Overall isn't it better to just have one parameter for which you can set a list of values like: 'Detach', 'DeleteAll', 'DeleteResources', etc.

For example if you have set things to detach and you specify -DeleteResourceGroups switch only you get error that resources cannot be to detach but resource groups to delete. If you set all 3 switches you will not get error but obviously it does not makes sense to add them all 3. 
Alternatively you could implement PowerShell parameters sets so when you have added -DeleteAll for example -DeleteResourceGroups or -DeleteResources do not appear anymore as option. Also is there a way that you can use only -DeleteResourceGroups without having to specify -DeleteResources as well? Because I am doing only subscription scope deployments may be I am missing some scenario.

**Describe alternatives you've considered**

**Additional context**

**Comment by aperezmicrosoft** [comment]
At the moment, we are not planning to revisit the parameter design. If this will impact you from leveraging Deployment Stacks, please let us know.
