### ISSUE TITLE
Can you set DenyStatus per resource?

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#84]
**Is your feature request related to a problem? Please describe.**
When you look at the managed resources you have the ID and DenyStatus for each resource. Is it possible to set different denyStatus per resource? I cannot remember if that was one of the goals for private preview 2.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snarkywolverine** [comment]
It is not possible for the user to specify a different deny setting for each resource. However, there are some scenarios where different resources in the same stack may have a different status (deny assignment failed to update, or a resource was created outside the scope of the deployment).  Therefore, we have denyStatus per-resource, even though the denySettings are per-stack.

Does that help clarify the usage?

**Comment by slavizh** [comment]
Yes, this clarifies it. Thanks!
