### ISSUE TITLE
Deployment Stacks resoure should support tags

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#86]
**Is your feature request related to a problem? Please describe.**
Deployment Stacks resource should support tags. Tags could allow you to specify important information that can be used also for filtering.

**Describe the solution you'd like**
Tags on Deployment stacks resources.

**Describe alternatives you've considered**

**Additional context**

**Comment by dantedallag** [comment]
Hey @slavizh this should be fixed in the new release. Can you try it out?

**Comment by slavizh** [comment]
@dantedallag confirming that is working and can be closed.
