### ISSUE TITLE
Missing instructions on installing the CLI on linux

### ISSUE THREAD

**Issue by codebytes** [Azure/deployment-stacks#95]
**Is your feature request related to a problem? Please describe.**
There are no instructions for the CLI on linux, there are for mac and windows

**Describe the solution you'd like**
Instructions for installing in linux so I can use inside a dev container

Happy to help document this and build the devcontainer

**Comment by aperezmicrosoft** [comment]
Thanks for pointing this out @codebytes. We are looking into the solution provided.
